In [1]:
import numpy as np
import numpy.random as random
from scipy.stats import norm

In [8]:
a = [1]*5
a

[1, 1, 1, 1, 1]

In [6]:
a= np.arange(10).reshape((5,2))
b = np.arange(5)
b_column = b[:, np.newaxis]
c = np.hstack((a, b_column))

In [ ]:
np.random.choice()

In [7]:
b.shape

(5,)

In [7]:
high_p = random.geometric(0.95,1000)
low_p = random.geometric(0.05, 1000)

np.mean(high_p), np.mean(low_p)

(np.float64(1.042), np.float64(19.527))

In [8]:
high_p.shape

(1000,)

In [4]:
class Square:

    @staticmethod
    def __call__(x: int):
        return x*x
    
Square()(5)

square = Square()
square(7)

49

In [3]:
a = np.arange(100)/100

for i, j in enumerate(a):
    print(f'{i}, {j}')

0, 0.0
1, 0.01
2, 0.02
3, 0.03
4, 0.04
5, 0.05
6, 0.06
7, 0.07
8, 0.08
9, 0.09
10, 0.1
11, 0.11
12, 0.12
13, 0.13
14, 0.14
15, 0.15
16, 0.16
17, 0.17
18, 0.18
19, 0.19
20, 0.2
21, 0.21
22, 0.22
23, 0.23
24, 0.24
25, 0.25
26, 0.26
27, 0.27
28, 0.28
29, 0.29
30, 0.3
31, 0.31
32, 0.32
33, 0.33
34, 0.34
35, 0.35
36, 0.36
37, 0.37
38, 0.38
39, 0.39
40, 0.4
41, 0.41
42, 0.42
43, 0.43
44, 0.44
45, 0.45
46, 0.46
47, 0.47
48, 0.48
49, 0.49
50, 0.5
51, 0.51
52, 0.52
53, 0.53
54, 0.54
55, 0.55
56, 0.56
57, 0.57
58, 0.58
59, 0.59
60, 0.6
61, 0.61
62, 0.62
63, 0.63
64, 0.64
65, 0.65
66, 0.66
67, 0.67
68, 0.68
69, 0.69
70, 0.7
71, 0.71
72, 0.72
73, 0.73
74, 0.74
75, 0.75
76, 0.76
77, 0.77
78, 0.78
79, 0.79
80, 0.8
81, 0.81
82, 0.82
83, 0.83
84, 0.84
85, 0.85
86, 0.86
87, 0.87
88, 0.88
89, 0.89
90, 0.9
91, 0.91
92, 0.92
93, 0.93
94, 0.94
95, 0.95
96, 0.96
97, 0.97
98, 0.98
99, 0.99


In [1]:
a= [1,2,3]
b = tuple(a)
b

(1, 2, 3)

In [4]:
class Market:
    dividends: np.ndarray
    price: float = 0.0
    last_period_price: float = 0.0
    demand_at_p0: float = np.inf
    last_price: float = 100
    mean_price: float = 100

    def __getitem__(self, key):
        """Allow dict-like access."""
        if isinstance(key, str):
            return getattr(self, key, None)
        raise KeyError(f"Invalid key: {key}")

market = Market()

market['last_price']


100

In [5]:
a= {'a': 1, 'b': 2, 'c': 3, 'd':4}
b = {}
b['a', 'b', 'c'] = 1,2,3
b['a']

KeyError: 'a'

In [11]:
a= np.arange(100).reshape(10,10)

for row in a:
    row[0] = 10
a 

array([[10,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [10, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [10, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [10, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [10, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [10, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [10, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
a = random.binomial(1, random.uniform(0,1,10), 10)
a

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [8]:
a = np.arange(10)
b = np.ones(10)

c = b/a
c

/tmp/ipykernel_55106/979902567.py:4: RuntimeWarning: divide by zero encountered in divide
  c = b/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [1]:
temp = {1: 'a', 2: 'b', 3: 'b'}
for key, value in temp.items():
    print(key, value)

1 a
2 b
3 b


In [9]:
from itertools import chain
a= {1: [[1,2], [1,2], [1,2]], 2: [[1,2], [1,2]], 3: [[1,2]]}
b = list(chain.from_iterable(a.values()))
b = np.array(b)
b

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
a= [[1,2,3], [1,2,3], [1,2,3]]
a = np.array(a)
type(a[0])

numpy.ndarray

In [30]:
a = np.ones((10, 5,2))
b = np.arange(5)
c = a[:,:,1]*b

c

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [19]:
a = np.arange(100).reshape(10,10)
b = np.arange(10)
c = a[:,2] * b
a[:,2], b,c

(array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([  0,  12,  44,  96, 168, 260, 372, 504, 656, 828]))

In [16]:
a[0][[3,4]]

array([3, 4])

In [ ]:
p =  random.uniform(0,1,100)
a = random.geometric(p)
a

array([ 1,  1,  1,  2,  3,  1,  1,  1,  1,  1,  1,  1, 24,  6,  1,  1,  1,
        1,  3,  1,  4,  5,  4,  2,  1,  1,  2,  1,  1,  3,  1,  1,  1,  1,
        2,  2, 21,  2,  3,  1,  2,  1,  3,  2,  3,  7,  2,  3, 36,  4,  1,
        1,  3,  1,  8,  1,  1, 30,  1,  1,  1, 31, 24,  1,  1,  2,  2,  3,
        1,  2,  1, 21,  5,  2,  5, 15,  2,  5,  1,  1,  4,  2,  4,  3,  1,
        2,  1,  2,  1,  2,  4,  4,  3, 41,  1,  4,  1,  1,  4,  6])

In [4]:
a = 0.05
a /= 2

mu = 0
sigma = 1

bid_price = mu + sigma * norm.ppf(a)
ask_price = mu + sigma*norm.ppf(1-a)

bid_price, ask_price

(np.float64(-1.9599639845400545), np.float64(1.959963984540054))

In [3]:
a = np.ones((10,2))

a[:,0].sum()

np.float64(10.0)

In [5]:
a = [(1,1),(2,2),(3,3)]
a = np.array(a)
a[:,0].sum()

np.int64(6)

In [13]:
random.uniform(0, -5)

-1.3763371249660001

In [4]:
from entities.agent import AgentInfo

In [5]:
columns = ['agent_type','id','demand','demand_function','fitness','objective_function','utility_function','learning_algorithm','risk_aversion','informed','signal','beta0','beta1','crossover_rate','mutation_rate']
agent = AgentInfo(columns=columns)

In [8]:
agent.utility_function

6

In [2]:
from typing import NamedTuple

class Demo(NamedTuple):
    a: int
    b: int
    c: int

test = Demo(1, 2, 3)

test['a']

TypeError: tuple indices must be integers or slices, not str

In [3]:
temp = {'a': 1, 'b': 2, 'c': 3}

temp.a

AttributeError: 'dict' object has no attribute 'a'

In [ ]:
a = np.arange(1,101).reshape(10,10)
traders = np.where(a[:,0] > 0)
columns = np.array([4,8,9])
b = np.ones((10,3))
a[traders][:,columns] = b
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:

a = np.arange(1, 101).reshape(10, 10)
columns = np.array([4, 8, 9])
b = np.ones((10, 3))

# Correct way: Use boolean mask directly
traders = np.where(a[:, 0] > 0)[0]  # Extract integer indices
a[traders[:, None], columns] = b  # Correct in-place modification
a

array([[ 1,  2,  3,  4,  1,  6,  7,  8,  1,  1],
       [11, 12, 13, 14,  1, 16, 17, 18,  1,  1],
       [21, 22, 23, 24,  1, 26, 27, 28,  1,  1],
       [31, 32, 33, 34,  1, 36, 37, 38,  1,  1],
       [41, 42, 43, 44,  1, 46, 47, 48,  1,  1],
       [51, 52, 53, 54,  1, 56, 57, 58,  1,  1],
       [61, 62, 63, 64,  1, 66, 67, 68,  1,  1],
       [71, 72, 73, 74,  1, 76, 77, 78,  1,  1],
       [81, 82, 83, 84,  1, 86, 87, 88,  1,  1],
       [91, 92, 93, 94,  1, 96, 97, 98,  1,  1]])

In [ ]:
traders = np.where(a[:,0] > 0)
columns = np.array([4,8,9])
b = np.ones((10,3))
a[traders][:,columns] = b
a[traders][:,columns]

array([[  5,   9,  10],
       [ 15,  19,  20],
       [ 25,  29,  30],
       [ 35,  39,  40],
       [ 45,  49,  50],
       [ 55,  59,  60],
       [ 65,  69,  70],
       [ 75,  79,  80],
       [ 85,  89,  90],
       [ 95,  99, 100]])

In [ ]:

b = np.ones((10,3))
a[traders][:,columns] = b

b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a[traders][:,columns] = b
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [3]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om

In [1]:
from entities.market import RoutledgeMarket

In [2]:
market = RoutledgeMarket()
json.load(open('assets/testing/components.json'))


exp = Experiment(market, 'assets/testing/agents.csv', 'assets/testing/components.json')

TypeError: '<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html