In [2]:
import numpy as np
import numpy.random as random

In [3]:
a = np.ones((10,2))

a[:,0].sum()

np.float64(10.0)

In [5]:
a = [(1,1),(2,2),(3,3)]
a = np.array(a)
a[:,0].sum()

np.int64(6)

In [13]:
random.uniform(0, -5)

-1.3763371249660001

In [4]:
from entities.agent import AgentInfo

In [5]:
columns = ['agent_type','id','demand','demand_function','fitness','objective_function','utility_function','learning_algorithm','risk_aversion','informed','signal','beta0','beta1','crossover_rate','mutation_rate']
agent = AgentInfo(columns=columns)

In [8]:
agent.utility_function

6

In [ ]:
if agen
    print('None')

AttributeError: 'AgentInfo' object has no attribute 'attributes'

In [2]:
from typing import NamedTuple

class Demo(NamedTuple):
    a: int
    b: int
    c: int

test = Demo(1, 2, 3)

test['a']

TypeError: tuple indices must be integers or slices, not str

In [3]:
temp = {'a': 1, 'b': 2, 'c': 3}

temp.a

AttributeError: 'dict' object has no attribute 'a'

In [ ]:
a = np.arange(1,101).reshape(10,10)
traders = np.where(a[:,0] > 0)
columns = np.array([4,8,9])
b = np.ones((10,3))
a[traders][:,columns] = b
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:

a = np.arange(1, 101).reshape(10, 10)
columns = np.array([4, 8, 9])
b = np.ones((10, 3))

# Correct way: Use boolean mask directly
traders = np.where(a[:, 0] > 0)[0]  # Extract integer indices
a[traders[:, None], columns] = b  # Correct in-place modification
a

array([[ 1,  2,  3,  4,  1,  6,  7,  8,  1,  1],
       [11, 12, 13, 14,  1, 16, 17, 18,  1,  1],
       [21, 22, 23, 24,  1, 26, 27, 28,  1,  1],
       [31, 32, 33, 34,  1, 36, 37, 38,  1,  1],
       [41, 42, 43, 44,  1, 46, 47, 48,  1,  1],
       [51, 52, 53, 54,  1, 56, 57, 58,  1,  1],
       [61, 62, 63, 64,  1, 66, 67, 68,  1,  1],
       [71, 72, 73, 74,  1, 76, 77, 78,  1,  1],
       [81, 82, 83, 84,  1, 86, 87, 88,  1,  1],
       [91, 92, 93, 94,  1, 96, 97, 98,  1,  1]])

In [ ]:
traders = np.where(a[:,0] > 0)
columns = np.array([4,8,9])
b = np.ones((10,3))
a[traders][:,columns] = b
a[traders][:,columns]

array([[  5,   9,  10],
       [ 15,  19,  20],
       [ 25,  29,  30],
       [ 35,  39,  40],
       [ 45,  49,  50],
       [ 55,  59,  60],
       [ 65,  69,  70],
       [ 75,  79,  80],
       [ 85,  89,  90],
       [ 95,  99, 100]])

In [ ]:

b = np.ones((10,3))
a[traders][:,columns] = b

b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a[traders][:,columns] = b
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [3]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om

In [1]:
from entities.market import RoutledgeMarket

In [2]:
market = RoutledgeMarket()
json.load(open('assets/testing/components.json'))


exp = Experiment(market, 'assets/testing/agents.csv', 'assets/testing/components.json')

TypeError: '<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html